# Generated by Django 4.0.3 on 2022-03-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logcollectionmodule',
            options={'verbose_name': 'Log Collection', 'verbose_name_plural': 'Log Collection'},
        ),
        migrations.AlterModelOptions(
            name='onpremmodule',
            options={'verbose_name': 'Onprem Module', 'verbose_name_plural': 'Onprem Module'},
        ),
        migrations.AlterModelOptions(
            name='setupstatic',
            options={'verbose_name': 'Setup Static', 'verbose_name_plural': 'Setup Static'},
        ),
        migrations.CreateModel(
            name='ProxySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxy',
            },
        ),
    ]
