# Generated by Django 4.0.3 on 2022-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_logcollectionmodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremmodule',
            name='device_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onpremmodule',
            name='device_hostname_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onpremmodule',
            name='device_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onpremmodule',
            name='device_port_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onpremmodule',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
