# Generated by Django 4.0.3 on 2022-03-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_onpremmodule_device_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onpremmodule',
            name='device_api_key',
        ),
        migrations.RemoveField(
            model_name='onpremmodule',
            name='device_hostname_ip',
        ),
        migrations.RemoveField(
            model_name='onpremmodule',
            name='device_port_name',
        ),
    ]
