# Generated by Django 4.0.3 on 2022-03-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_onpremmodule_device_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onpremmodule',
            name='device_prodcut',
            field=models.CharField(blank=True, choices=[('Checkpoint', 'Checkpoint'), ('Cisco AsIa', 'Cisco ASA'), ('Deep Security', 'Deep Security'), ('PalaAlto', 'PalaAlto')], max_length=255, null=True),
        ),
    ]
