# Generated by Django 4.0.3 on 2022-03-22 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_remove_onpremmodule_sporact_api_key_onpremkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcollectionmodule',
            name='apex_one',
        ),
        migrations.RemoveField(
            model_name='logcollectionmodule',
            name='deep_security',
        ),
        migrations.RemoveField(
            model_name='logcollectionmodule',
            name='secret_key_sub_config',
        ),
        migrations.RemoveField(
            model_name='logcollectionmodule',
            name='sporact_webhook_key',
        ),
        migrations.RemoveField(
            model_name='logcollectionmodule',
            name='sporact_webhook_url',
        ),
        migrations.RemoveField(
            model_name='logcollectionmodule',
            name='udp_port',
        ),
        migrations.CreateModel(
            name='LogCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udp_port', models.IntegerField(blank=True, default=0, null=True)),
                ('sporact_webhook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sporact_webhook_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeepSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key_sub_config', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
