# Generated by Django 4.0.3 on 2022-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_setuphost'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremmodule',
            name='sporact_webhook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
